"""empty message

Revision ID: 09d5d3b371d1
Revises: 
Create Date: 2021-03-11 12:55:07.572630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d5d3b371d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('php_eligibility',
    sa.Column('member_ID', sa.String(length=20), nullable=False),
    sa.Column('eligibility', sa.String(length=10), nullable=True),
    sa.Column('thruDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('member_ID')
    )
    op.create_table('php_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('php_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('icd1', sa.String(length=10), nullable=True),
    sa.Column('icd2', sa.String(length=10), nullable=True),
    sa.Column('icd3', sa.String(length=10), nullable=True),
    sa.Column('icd4', sa.String(length=10), nullable=True),
    sa.Column('icd5', sa.String(length=10), nullable=True),
    sa.Column('icd6', sa.String(length=10), nullable=True),
    sa.Column('icd7', sa.String(length=10), nullable=True),
    sa.Column('CPT1', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit1', sa.Integer(), nullable=True),
    sa.Column('CPT2', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit2', sa.Integer(), nullable=True),
    sa.Column('CPT3', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit3', sa.Integer(), nullable=True),
    sa.Column('CPT4', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit4', sa.Integer(), nullable=True),
    sa.Column('CPT5', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit5', sa.Integer(), nullable=True),
    sa.Column('CPT6', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit6', sa.Integer(), nullable=True),
    sa.Column('CPT7', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit7', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('php_pending_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_ID', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('refNumber', sa.String(length=30), nullable=False),
    sa.Column('submittedDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=30), nullable=False),
    sa.Column('case', sa.String(length=30), nullable=True),
    sa.Column('emr', sa.String(length=30), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['member_ID'], ['php_eligibility.member_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('php_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_ID', sa.String(length=20), nullable=False),
    sa.Column('caseName', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('icd1', sa.String(length=20), nullable=True),
    sa.Column('icd2', sa.String(length=20), nullable=True),
    sa.Column('icd3', sa.String(length=20), nullable=True),
    sa.Column('icd4', sa.String(length=20), nullable=True),
    sa.Column('icd5', sa.String(length=20), nullable=True),
    sa.Column('icd6', sa.String(length=20), nullable=True),
    sa.Column('icd7', sa.String(length=20), nullable=True),
    sa.Column('CPT1', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit1', sa.Integer(), nullable=True),
    sa.Column('CPT2', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit2', sa.Integer(), nullable=True),
    sa.Column('CPT3', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit3', sa.Integer(), nullable=True),
    sa.Column('CPT4', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit4', sa.Integer(), nullable=True),
    sa.Column('CPT5', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit5', sa.Integer(), nullable=True),
    sa.Column('CPT6', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit6', sa.Integer(), nullable=True),
    sa.Column('CPT7', sa.String(length=20), nullable=True),
    sa.Column('CPTUnit7', sa.Integer(), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=True),
    sa.Column('emr', sa.Boolean(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('files', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submissionMessage', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['member_ID'], ['php_eligibility.member_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medi_cal_pending_request', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('medi_cal_pending_request', sa.Column('firstName', sa.String(length=20), nullable=True))
    op.add_column('medi_cal_pending_request', sa.Column('lastName', sa.String(length=20), nullable=True))
    op.add_column('medi_cal_request', sa.Column('dob', sa.DateTime(), nullable=True))
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('medi_cal_request', 'dob')
    op.drop_column('medi_cal_pending_request', 'lastName')
    op.drop_column('medi_cal_pending_request', 'firstName')
    op.drop_column('medi_cal_pending_request', 'dob')
    op.drop_table('php_request')
    op.drop_table('php_pending_request')
    op.drop_table('php_template')
    op.drop_table('php_settings')
    op.drop_table('php_eligibility')
    # ### end Alembic commands ###
