"""empty message

Revision ID: 34fbea4741ac
Revises: dd84b203918b
Create Date: 2021-03-18 12:26:09.027977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fbea4741ac'
down_revision = 'dd84b203918b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hpsj_eligibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=20), nullable=True))

    with op.batch_alter_table('hpsj_pending_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('emr_entry', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=20), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('hpsj_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caseName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=True))

    with op.batch_alter_table('hpsj_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=True))

    with op.batch_alter_table('prime_eligibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=20), nullable=True))

    with op.batch_alter_table('prime_pending_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('emr_entry', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=20), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('prime_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caseName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=True))

    with op.batch_alter_table('prime_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prime_template', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    with op.batch_alter_table('prime_request', schema=None) as batch_op:
        batch_op.drop_column('frequency')
        batch_op.drop_column('emr')
        batch_op.drop_column('caseName')

    with op.batch_alter_table('prime_pending_request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('emr_entry')
        batch_op.drop_column('case')

    with op.batch_alter_table('prime_eligibility', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('hpsj_template', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    with op.batch_alter_table('hpsj_request', schema=None) as batch_op:
        batch_op.drop_column('frequency')
        batch_op.drop_column('caseName')

    with op.batch_alter_table('hpsj_pending_request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('emr_entry')
        batch_op.drop_column('dob')
        batch_op.drop_column('case')

    with op.batch_alter_table('hpsj_eligibility', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
