"""empty message

Revision ID: 734ee3075956
Revises: 09d5d3b371d1
Create Date: 2021-03-13 18:15:51.612473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734ee3075956'
down_revision = '09d5d3b371d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('php_pending_request', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('php_pending_request', 'refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('php_pending_request', 'refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('php_pending_request', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
