"""empty message

Revision ID: 74952b69ebc2
Revises: f217d60d0357
Create Date: 2021-03-15 15:17:39.521690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74952b69ebc2'
down_revision = 'f217d60d0357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medi_cal_pending_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emr_entry', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medi_cal_pending_request', schema=None) as batch_op:
        batch_op.drop_column('emr_entry')

    # ### end Alembic commands ###
