"""empty message

Revision ID: bd92f244a2cd
Revises: d807720dfe1c
Create Date: 2021-03-14 16:06:02.136415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd92f244a2cd'
down_revision = 'd807720dfe1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medi_cal_request', schema=None) as batch_op:
        batch_op.alter_column('onsetDate',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('php_pending_request', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('php_pending_request', schema=None) as batch_op:
        batch_op.alter_column('refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('medi_cal_request', schema=None) as batch_op:
        batch_op.alter_column('prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('onsetDate',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
