"""empty message

Revision ID: bf65850470ba
Revises: 734ee3075956
Create Date: 2021-03-14 15:54:01.004509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf65850470ba'
down_revision = '734ee3075956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('php_eligibility', sa.Column('other_ins', sa.String(length=20), nullable=True))
    op.alter_column('php_pending_request', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('php_pending_request', 'refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('php_pending_request', 'refNumber',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('php_pending_request', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('php_eligibility', 'other_ins')
    op.alter_column('medi_cal_request', 'prescriptionDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('medi_cal_request', 'onsetDate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
