"""empty message

Revision ID: d66ff3dd4df3
Revises: 74952b69ebc2
Create Date: 2021-03-15 15:30:16.184901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66ff3dd4df3'
down_revision = '74952b69ebc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('php_pending_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emr_entry', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('php_pending_request', schema=None) as batch_op:
        batch_op.drop_column('emr_entry')

    # ### end Alembic commands ###
