"""empty message

Revision ID: f217d60d0357
Revises: bd92f244a2cd
Create Date: 2021-03-14 17:03:52.496931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f217d60d0357'
down_revision = 'bd92f244a2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('php_eligibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('php_eligibility', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
